# Generated by Django 4.2.16 on 2024-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="pf_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Наименование в PowerFactory",
            ),
        ),
        migrations.AddField(
            model_name="substation",
            name="pf_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Наименование в PowerFactory",
            ),
        ),
    ]
