# Generated by Django 4.2.16 on 2024-11-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_protectiondevice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectiondevice",
            name="components",
            field=models.ManyToManyField(
                related_name="protection_devices",
                to="core.component",
                verbose_name="Органы ДФЗ",
            ),
        ),
        migrations.DeleteModel(
            name="DeviceEquipment",
        ),
    ]
