# Generated by Django 4.2.16 on 2024-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_protectiondevice_components_delete_deviceequipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="voltage_transformer_ratio",
            field=models.FloatField(
                blank=True,
                default=5000,
                null=True,
                verbose_name="Коэффициент трансформации ТН",
            ),
        ),
    ]
