# Generated by Django 4.2.16 on 2025-12-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_coefficienttype_currenttransformer_linetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="index_pf",
            field=models.IntegerField(
                blank=True,
                help_text="Индекс линии в списке всех линий PowerFactory (ElmBranch)",
                null=True,
                verbose_name="Индекс линии в PowerFactory",
            ),
        ),
    ]
