# Generated by Django 4.2.16 on 2025-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_change_length_voltage_to_decimal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linebranch",
            name="dispatch_name",
        ),
        migrations.RemoveField(
            model_name="linebranch",
            name="length",
        ),
        migrations.RemoveField(
            model_name="linebranch",
            name="pf_name",
        ),
        migrations.RemoveField(
            model_name="substation",
            name="dispatch_name",
        ),
        migrations.AddField(
            model_name="linebranch",
            name="pf_name_substation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя подстанции ответвления из PowerFactory",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Подстанция ответвления",
            ),
        ),
        migrations.AlterField(
            model_name="linebranch",
            name="protection_recommendation",
            field=models.TextField(
                blank=True,
                default="Нет необходимости",
                null=True,
                verbose_name="Рекомендация по установке доп. комплекта защиты на ответвлении",
            ),
        ),
        migrations.AlterField(
            model_name="substation",
            name="pf_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя подстанции из PowerFactory",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Наименование в PowerFactory",
            ),
        ),
    ]
