# Generated by Django 4.2.16 on 2025-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_linebranch_dispatch_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="r0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Активное сопротивление нулевой последовательности, получаемое из PowerFactory",
                max_digits=10,
                null=True,
                verbose_name="Сопротивление нулевой последовательности, Ом",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="r1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Активное сопротивление прямой последовательности, получаемое из PowerFactory",
                max_digits=10,
                null=True,
                verbose_name="Сопротивление прямой последовательности, Ом",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="x0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Реактивное сопротивление нулевой последовательности, получаемое из PowerFactory",
                max_digits=10,
                null=True,
                verbose_name="Реактивное сопротивление нулевой последовательности, Ом",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="x1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Реактивное сопротивление прямой последовательности, получаемое из PowerFactory",
                max_digits=10,
                null=True,
                verbose_name="Реактивное сопротивление прямой последовательности, Ом",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="z0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Модуль полного сопротивления нулевой последовательности (Z0 = sqrt(R0² + X0²))",
                max_digits=10,
                null=True,
                verbose_name="Полное сопротивление нулевой последовательности, Ом",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="z1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Модуль полного сопротивления прямой последовательности (Z1 = sqrt(R1² + X1²))",
                max_digits=10,
                null=True,
                verbose_name="Полное сопротивление прямой последовательности, Ом",
            ),
        ),
    ]
