# Generated by Django 4.2.16 on 2025-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_line_r0_line_r1_line_x0_line_x1_line_z0_line_z1"),
    ]

    operations = [
        migrations.AddField(
            model_name="linebranch",
            name="pf_name_line",
            field=models.CharField(
                blank=True,
                help_text="Имя линии из PowerFactory (копия line.pf_name для удобства поиска)",
                max_length=100,
                null=True,
                verbose_name="Имя ЛЭП в PowerFactory",
            ),
        ),
        migrations.AlterField(
            model_name="linebranch",
            name="pf_name_substation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя подстанции ответвления из PowerFactory",
                max_length=100,
                null=True,
                verbose_name="Подстанция ответвления",
            ),
        ),
        migrations.AlterField(
            model_name="linebranch",
            name="substation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_branches",
                to="core.substation",
                verbose_name="Подстанция",
            ),
        ),
    ]
