# Generated by Django 4.2.16 on 2025-12-18 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_methodology_url_methodologydocument_name_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="methodology",
        ),
        migrations.RemoveField(
            model_name="protectiondevice",
            name="manufacturer",
        ),
    ]
