# Generated by Django 4.2.16 on 2025-12-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_manufacturer_methodology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="project_name",
            field=models.CharField(
                blank=True,
                help_text="Имя проекта PowerFactory, из которого импортирована линия",
                max_length=200,
                null=True,
                verbose_name="Имя проекта PowerFactory",
            ),
        ),
        migrations.AddField(
            model_name="substation",
            name="project_name",
            field=models.CharField(
                blank=True,
                help_text="Имя проекта PowerFactory, из которого импортирована подстанция",
                max_length=200,
                null=True,
                verbose_name="Имя проекта PowerFactory",
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="dispatch_name",
            field=models.CharField(
                max_length=100, verbose_name="Диспетчерское наименование"
            ),
        ),
        migrations.AlterField(
            model_name="substation",
            name="pf_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя подстанции из PowerFactory",
                max_length=100,
                null=True,
                verbose_name="Наименование в PowerFactory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("pf_name", "project_name")},
        ),
        migrations.AlterUniqueTogether(
            name="substation",
            unique_together={("pf_name", "project_name")},
        ),
    ]
