# Generated by Django 4.2.16 on 2026-02-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_increase_dispatch_name_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="pf_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Наименование в PF.Protection",
            ),
        ),
        migrations.AlterField(
            model_name="substation",
            name="pf_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя подстанции из PowerFactory",
                max_length=100,
                null=True,
                verbose_name="Наименование в PF.Protection",
            ),
        ),
    ]
