# Generated by Django 4.2.16 on 2024-11-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер расчета"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата расчета"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мета-данные расчета",
                "verbose_name_plural": "Мета-данные расчетов",
            },
        ),
        migrations.CreateModel(
            name="CalculationProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.FloatField(verbose_name="Результат расчета")),
                (
                    "calculation_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="calculation.calculationmeta",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="core.component",
                    ),
                ),
                (
                    "protection_half_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="core.protectionhalfset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол расчета",
                "verbose_name_plural": "Протоколы расчетов",
            },
        ),
    ]
