# Generated by Django 4.2.16 on 2024-11-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("calculation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fault_type", models.CharField(max_length=255, verbose_name="Вид КЗ")),
                (
                    "fault_location",
                    models.CharField(max_length=255, verbose_name="Узел КЗ"),
                ),
                (
                    "network_topology",
                    models.CharField(max_length=255, verbose_name="Схема сети"),
                ),
                (
                    "fault_currents",
                    models.JSONField(verbose_name="Токи симметричных составляющих"),
                ),
                (
                    "calculation_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faults",
                        to="calculation.calculationmeta",
                    ),
                ),
                (
                    "protection_half_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faults",
                        to="core.protectionhalfset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол расчета КЗ",
                "verbose_name_plural": "Протоколы расчетов КЗ",
            },
        ),
    ]
