# Generated by Django 4.2.16 on 2024-11-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_line_pf_name_substation_pf_name"),
        ("calculation", "0002_faultcalculation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultCalculationProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fault_type", models.CharField(max_length=255, verbose_name="Вид КЗ")),
                (
                    "fault_location",
                    models.CharField(max_length=255, verbose_name="Узел КЗ"),
                ),
                (
                    "network_topology",
                    models.CharField(max_length=255, verbose_name="Схема сети"),
                ),
                (
                    "positive_sequence_current",
                    models.FloatField(verbose_name="Ток прямой последовательности"),
                ),
                (
                    "negative_sequence_current",
                    models.FloatField(verbose_name="Ток обратной последовательности"),
                ),
                (
                    "protection_half_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faults",
                        to="core.protectionhalfset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол расчета КЗ",
                "verbose_name_plural": "Протоколы расчетов КЗ",
            },
        ),
        migrations.CreateModel(
            name="SensitivityAnalysisProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensitivity_rate",
                    models.FloatField(verbose_name="Коэффициент чувствительности"),
                ),
                (
                    "fault_calculation_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculation.faultcalculationprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ чувствительности",
                "verbose_name_plural": "Анализ чувствительности",
            },
        ),
        migrations.RenameModel(
            old_name="CalculationProtocol",
            new_name="SettingsCalculationProtocol",
        ),
        migrations.DeleteModel(
            name="FaultCalculation",
        ),
        migrations.AddField(
            model_name="sensitivityanalysisprotocol",
            name="settings_calculation_protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calculation.settingscalculationprotocol",
            ),
        ),
    ]
