# Generated by Django 4.2.16 on 2024-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0004_fault_faultcalculation_faultprotection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faultprotection",
            name="component",
        ),
        migrations.RemoveField(
            model_name="faultprotection",
            name="fault",
        ),
        migrations.AlterField(
            model_name="faultcalculation",
            name="fault_type",
            field=models.CharField(max_length=255, verbose_name="Вид КЗ"),
        ),
        migrations.DeleteModel(
            name="Fault",
        ),
        migrations.DeleteModel(
            name="FaultProtection",
        ),
    ]
