# Generated by Django 4.2.16 on 2024-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0005_remove_faultprotection_component_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingscalculation",
            name="calculation_factors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
