# Generated by Django 4.2.16 on 2024-12-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_calculationmeta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultcalculation',
            name='calculation_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.calculationmeta'),
        ),
    ]
