# Generated by Django 4.2.16 on 2025-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_faultcalculation_calculation_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivityanalysis',
            name='status',
            field=models.CharField(choices=[('Нечувствительна', 'Нечувствительна'), ('Низкая чувствительность', 'Низкая чувствительность'), ('Чувствительность', 'Чувствительность')], default='Нечувствительна', max_length=255, verbose_name='Статус'),
        ),
    ]
