# Generated by Django 4.2.16 on 2025-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0009_sensitivityanalysis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingscalculation",
            name="primary_value",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Значение уставки в первичных величинах",
            ),
        ),
        migrations.AddField(
            model_name="settingscalculation",
            name="secondary_value",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Значение уставки во вторичных величинах",
            ),
        ),
        migrations.AlterField(
            model_name="settingscalculation",
            name="result_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Результат расчета"
            ),
        ),
    ]
