# Generated by Django 4.2.16 on 2025-12-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_methodology_url_methodologydocument_name_file_and_more"),
        ("calculation", "0010_settingscalculation_primary_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HalfSetSubmode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submode_name",
                    models.CharField(max_length=255, verbose_name="Название подрежима"),
                ),
                (
                    "submode_elements",
                    models.JSONField(
                        help_text="Список full_name элементов в формате JSON",
                        verbose_name="Элементы подрежима",
                    ),
                ),
                (
                    "generation_params",
                    models.JSONField(
                        blank=True,
                        help_text="Параметры, при которых был сгенерирован подрежим",
                        null=True,
                        verbose_name="Параметры генерации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "protection_half_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submodes",
                        to="core.protectionhalfset",
                        verbose_name="Полукомплект защиты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подрежим полукомплекта",
                "verbose_name_plural": "Подрежимы полукомплектов",
                "unique_together": {("protection_half_set", "submode_name")},
            },
        ),
    ]
