# Generated by Django 4.2.16 on 2026-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0011_halfsetsubmode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensitivityanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("Нечувствительна", "Нечувствительна"),
                    ("Низкая чувствительность", "Низкая чувствительность"),
                    ("Чувствительна", "Чувствительна"),
                ],
                default="Нечувствительна",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
